[pytest]
# plugin configuration for pytest
# Two plugins are used: 
#   pytest-html for HTML reports 
#   and pytest-xdist for parallel test execution
#   The `-n auto` option allows pytest to automatically 
#   determine the number of CPUs available for parallel execution
addopts = 
    --html=./report/report.html
    -n auto
# specify the directory where tests are located
testpaths = tests
# specify the patterns for test discovery
python_files = test_*.py
python_classes = Test*
python_functions = test_*
# Define custom markers to categorize tests
#   smoke: marks basic functionality tests that act as quick checks for core features
# - regression: marks tests designed to catch reintroduced bugs (i.e., verify past issues stay fixed).
markers =
    smoke: marks basic functionality tests (smoke tests)
    regression: marks tests for verifying bug fixes (regression tests)
